In [1]:
import nltk
from sklearn.feature_extraction import FeatureHasher

In [2]:
# create a FeatureHasher with support for one feature

hasher = FeatureHasher(n_features=1, input_type="string", alternate_sign=False)

In [3]:
hasher.fit_transform([['dog']]).toarray()

array([[1.]])

In [4]:
hasher.fit_transform([['cat']]).toarray()

array([[1.]])

In [5]:
# create a FeatureHasher with support for two features

hasher = FeatureHasher(n_features=2, input_type="string", alternate_sign=False)

In [6]:
hasher.fit_transform([['dog']]).toarray()

array([[0., 1.]])

In [7]:
hasher.fit_transform([['cat']]).toarray()

array([[0., 1.]])

In [8]:
# create a FeatureHasher with support for three features

hasher = FeatureHasher(n_features=3, input_type="string", alternate_sign=False)

In [9]:
hasher.fit_transform([['dog']]).toarray()

array([[1., 0., 0.]])

In [10]:
hasher.fit_transform([['cat']]).toarray()

array([[0., 1., 0.]])

In [11]:
hasher.fit_transform([['fish']]).toarray()

array([[0., 0., 1.]])

In [12]:
hasher.fit_transform([['bird']]).toarray()

array([[0., 1., 0.]])

In [13]:
# create a FeatureHasher with support for four features

hasher = FeatureHasher(n_features=4, input_type="string", alternate_sign=False)

In [14]:
hasher.fit_transform([['dog']]).toarray()

array([[0., 1., 0., 0.]])

In [15]:
hasher.fit_transform([['cat']]).toarray()

array([[0., 0., 0., 1.]])

In [16]:
hasher.fit_transform([['fish']]).toarray()

array([[0., 0., 0., 1.]])

In [17]:
hasher.fit_transform([['bird']]).toarray()

array([[0., 1., 0., 0.]])

In [18]:
# create a FeatureHasher with support for eight features

hasher = FeatureHasher(n_features=16, input_type="string", alternate_sign=False)

In [19]:
hasher.fit_transform([['dog']]).toarray()

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
hasher.fit_transform([['cat']]).toarray()

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
hasher.fit_transform([['fish']]).toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
hasher.fit_transform([['bird']]).toarray()

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
# hash list with items of different lengths and combinations

hasher.fit_transform([['dog'], ['dog', 'cat'], ['dog', 'cat', 'bird'], ['dog', 'dog']]).toarray()

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
from sklearn.feature_extraction.text import HashingVectorizer

In [25]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\maxen\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [26]:
corpus = [ "The early bird gets the worm." ]

In [27]:
vectorizer = HashingVectorizer(n_features = 16)
vectorizer

HashingVectorizer(alternate_sign=True, analyzer='word', binary=False,
                  decode_error='strict', dtype=<class 'numpy.float64'>,
                  encoding='utf-8', input='content', lowercase=True,
                  n_features=16, ngram_range=(1, 1), norm='l2',
                  preprocessor=None, stop_words=None, strip_accents=None,
                  token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None)

In [28]:
vect = vectorizer.fit_transform(corpus)
vect.shape

(1, 16)

In [29]:
vect.toarray()

array([[ 0.35355339, -0.35355339,  0.        ,  0.        ,  0.        ,
         0.        ,  0.35355339,  0.        ,  0.        ,  0.        ,
        -0.35355339,  0.        ,  0.        ,  0.        , -0.70710678,
         0.        ]])